CREATE PROCEDURE [DBO].[CONSULTAORCAMENTO]  
  
(  
 @DATAINICIO DATE = NULL,
 @DATAFIM DATE = NULL,
 @IDORCAMENTO INT = 0, 
 @IDCLIENTE INT = 0,
 @SITUACAO INT = 2 --TODAS   
)  
AS  
  SELECT * FROM ORCAMENTO
  WHERE (@DATAINICIO IS NULL OR DATAORCAMENTO BETWEEN @DATAINICIO AND @DATAFIM)
  AND (@IDCLIENTE = 0 OR CLIENTEID = @IDCLIENTE)
  AND (@IDORCAMENTO = 0 OR ORCAMENTOID =  @IDORCAMENTO )
  AND (@SITUACAO = 2 OR SITUACAO = @SITUACAO)
  
  